id: P1827D5DA
initial_creation_type: input
source_metadata:
  title: Middle Way Series
  language: en
  description: 'The following texts are available as part of our series on the Middle
    Way (Madhyamaka/Mādhyamika; dbu ma) philosophy:'
  volume:
    720b61497f48425c9f6f88384236663a:
      title: Conveying the Essence of the Middle Way of Consequence
      parent: General
    9fc258942a6447ce82d17ad47c0add5d:
      title: 'The Words of Candra: The Definitive Secret of the Great Middle Way of
        Consequence Beyond Extremes, the Fundamental Intent of All the Tathāgatas'
      parent: General
    b0e2bba8a22741de9352410a5c1c6a4e:
      title: 'The Seed of Reasoning: Notes on the Five Great Logical Arguments of
        the Middle Way'
      parent: General
    9e91a34bc3e84476b40406294f069dff:
      title: A Step-by-Step Meditation on the Definitive Meaning of the Great Middle
        Way
      parent: General
    12e8ff3d06744bd0987d84b003247a9f:
      title: 'Gateway to Learning: Four Great Logical Arguments of the Middle Way'
      parent: General
    b75f5073ceef45f5a5ff1b169c26458e:
      title: Profound Instruction on the View of the Middle Way
      parent: General
    a8eb78bfc5b943ccb0aa0142c6b2f0bc:
      title: 'Clarifying the Essence: A Summary of the Instructions on the View of
        the Middle Way'
      parent: General
    3142dca88db045c89c6c2a7d830b3433:
      title: Commentary on the Madhyamakāvatāra—Part 1—Collection of Reasoning
      parent: Madhyamakāvatāra
    43f4a241bbf741f8ae9fe448444149a6:
      title: Commentary on the Madhyamakāvatāra—Part 2—Title and Translators Homage
      parent: Madhyamakāvatāra
    f03ce0f67c4842eaab73317e917c1ce8:
      title: Prologue to Introduction to the Middle Way (Madhyamakāvatāra)
      parent: Madhyamakāvatāra
    79ffbe5e590e42a1b75de1d0dbb34b57:
      title: Concise Middle Way Aspiration
      parent: Prayers
    b4ee601df0c54660bae507469b2a4f6b:
      title: Middle Way Aspiration
      parent: Prayers
created_at: '2022-03-01T04:42:52.487407'
last_modified_at: '2022-03-01T04:42:52.487413'
